### ISSUE TITLE
Installing the shared library correctly

### ISSUE THREAD

**Issue by kzidane** [cs50/lib50-c#22]
@dmalan @glennholloway 

```
error while loading shared libraries: libcs50.so: cannot open shared object file: No such file or directory
```

it looks like shared libraries are not being searched for in `/usr/local/lib` by default. here are the solutions that I could find:

per http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
1. modify `LD_LIBRARY_PATH` (useful for testing and development; shouldn't be modified by installation process) — section 3.3.1.
2. copy libcs50.so to a standard dir (e.g., /usr/lib) and running `ldconfig`— section 3.5.

per a Unix SE question http://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib 
3. adding `/usr/local/lib` to `/etc/ld.so.conf` and running `ldconfig`.

per http://www.cyberciti.biz/faq/linux-setting-changing-library-path/
4. creating a conf file under the `/etc/ld.so.conf.d`, containing `/usr/local/lib`, and running `ldconfig`.

thoughts?

**Comment by dmalan** [comment]
(2) seems best for now. Reasonable since we're installing via a package
manager. Ultimately, should maybe go in /opt/cs50, but that'd require one
of the other steps too anyway. Is running `ldconfig` definitely necessary,
I assume in the after-install.sh script?

**Comment by kzidane** [comment]
@dmalan actually after more reading and grepping, turns out that `/usr/lib/local` is listed in `/etc/ld.so.conf/libc.conf`, so we probably should just call `ldconfig` in both, postinst (an after-install script) and postrm (an after-remove script), as per [this footnote](https://www.debian.org/doc/debian-policy/footnotes.html#f61):

> it is perfectly safe to invoke ldconfig unconditionally in a postinst, it is OK for a package to simply put ldconfig in its postinst without checking the argument.



> postrm, on the other hand, is called with the "remove" argument just after the files are removed, so this is the proper time to call "ldconfig" to notify the system of the fact that the shared libraries from the package are removed.

**Comment by crossroads1112** [comment]
I apologize if this is an ignorant question, but is there a reason that libcs50.so can't simply be put in `/usr/lib` as is the standard (on Linux anyway)?

**Comment by dmalan** [comment]
Ah, sounds good. In that case, should we use this as an opportunity to put
the library in `/opt/cs50/lib50-c` after all? Cf.
http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html. We could
then tell ldconfig to look in `/opt/cs50/lib50-c/lib` or even
`/opt/cs50/lib`. Though is there an analog for `#include`, whereby we could
configure the system to look in `/opt/cs50/lib50-c/include` or
`/opt/cs50/include` by default, rather than rely on `-I` in `$CFLAGS` or on
a symlink in /usr/include?

**Comment by dmalan** [comment]
@crossroads1112, just trying to adopt more consistent practices with our packages moving forward. Even though putting things in `/usr` isn't uncommon (indeed, we've done so for years ourselves), I've been trying to isolate our changes to base systems to `/opt` (and `/var/opt` and `/etc/opt` when we can), since our packages are "not part of the default installation," per http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html.

**Comment by crossroads1112** [comment]
Putting a library in `/opt` is a bit of an antipattern. Per [this](http://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-local) stack overflow question, `/opt` is for (often closed source) software installed in a monolithic fashion. I have yet to see a library installed there or in /etc or /var. `/usr/local` is for software installed by the administrator that is *not managed by the package manager* for the purposes of avoiding name conflicts. 

`/lib` is for 'essential' libraries that are intended to be used in single user mode while `/usr/lib` is for libraries to be used by user programs. This last distinction is a bit antiquated and comes from a time when it was common to have `/usr` on a separate partition or disk (perhaps to be shared across OSs) which is why you wouldn't want to have essential libraries in it. Some modern distributions even simply have `/lib` as a symlink to `/usr/lib`

To me it seems like `/usr/lib` is where the library should be installed as it is nonessential and is managed by the package manager.

**Comment by kzidane** [comment]
@dmalan 

after further searching and reading, I don't think `/opt` is ideal to use as well. most of the guides and SO posts that I've run through during the search recommend placing in `/usr/local/lib` or `/usr/lib`. 

per 3.2.1 File System Placement (http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html):

> Most open source software tends to follow the GNU standards



> The GNU standards recommend installing by default all libraries in /usr/local/lib when distributing source code (and all commands should go into /usr/local/bin)



on the other hand:
> According to the FHS, most libraries should be installed in /usr/lib

the section also points that there's no conflict between the two standards and that `/usr/local/lib` is the default for source code devs while `/usr/lib` is the default for distributors.

further more, FHS thinks (http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY) that the `/usr/local` hierarchy should be used by sysadmins for software needed to be safe from being overwritten when the system software is updated. the standard also suggests that `/usr/lib` includes libraries, in a general way (http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLIBLIBRARIESFORPROGRAMMINGANDPA).

**Comment by dmalan** [comment]
Okay, let's go with /usr/{lib,include,src}. I've pushed the changes!

Thanks, @crossroads1112!
