### ISSUE TITLE
Double Freeing

### ISSUE THREAD

**Issue by kzidane** [cs50/lib50-c#23]
@dmalan 

while testing, detected a bug in lib50-c caused by the use of `get_string` in other lib50-c functions. basically because we're freeing inside these functions as well as the destructor, we're double-freeing. 

assuming we still want to free `get_string` allocations, instead of calling `free` directly from these functions, good idea to use a linked-list-based data structure and have a `deallocate` function, that would take a string, search for it in the list, free, and update `allocations`?

something like:

```c
void deallocate(string s) {
    string_node *prev = NULL;
    string_node *curr = root;
    while (curr && curr->s != s) {
        prev = curr;
        curr = curr->next;
    }

    if (curr) {
        if (prev)
            prev->next = curr->next;
        else
            root = NULL;

       free(curr);
       allocations--;
    }
}
```

(pardon any oversights above, if any; written on the fly)

that would, of course, be slower and consume more space (actually we'd have to handle realloc'ing less memory, or we'd end up with unused space), but is there a better solution? using `scanf` instead of `get_string` perhaps? though may be a bit of a headache too?

**Comment by crossroads1112** [comment]
Since we are already using GNU extensions, why not `getline`? This to me seems like the best solution as it essentially does the exact same thing as `get_string`. In fact, perhaps it would be worth considering making `get_string` essentially a wrapper around `getline` that adds the allocated strings to the `strings` array? 

I don't think `scanf` should be used since it is way to easy to trigger undefined behavior. If we need to keep it standard C, fgets/sscanf could work?

**Comment by crossroads1112** [comment]
As an addendum to the above:

The declaration of `getline is as follows `ssize_t getline(char **lineptr, size_t *n, FILE *stream);`

`getline` can operate on preallocated buffers (it will resize them if necessary) or it can allocate its own. It could be used as such

    string buf = NULL;
    size_t size = 0;
    if (getline(&buf, &size, stdin) == -1)
    {
        return NULL;
    }

**Comment by IvanJasenov** [comment]
I think that the most elegant solution will be to mimic the architecture of
the IP packet, make the string a type which will consists header and
payload and pack the control into the array of pointers. Going with
ATM-like, design, fixed - size packets will waist to much memory. Just an
idea.

On Aug 9, 2016 16:26, "Chad Sharp" <notifications@github.com> wrote:

Since we are already using GNU extensions, why not getline? This to me
seems like the best solution as it essentially does the exact same thing as
get_string. In fact, perhaps it would be worth considering making get_string
essentially a wrapper around getline that adds the allocated strings to the
strings array?

I don't think scanf should be used since it is way to easy to trigger
undefined behavior. If we need to keep it standard C, fgets/sscanf could
work?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cs50/lib50-c/issues/23#issuecomment-238569866>, or mute
the thread

**Comment by dmalan** [comment]
@crossroads1112 would using `getline` break our newly added support for handling multiple line endings? In particular, we want to be able to hand CR, CRLF, and LF all on the same platform, not just in a per-platform way. We ran into an issue on HackerRank, for instance, where some test inputs had LF and some had CRLF, both on the same platform. It sometimes happens too that students create files on their Mac or PC, too, and then use them within a Linux environment, with unexpected (line ending-related) results.

**Comment by dmalan** [comment]
@IvanJasenov not sure that would help us in this situation, though. And it would actually complicate the definition of a `string` quite a bit, which right now is a nice abstraction of what, underneath the hood, is simply a `char *`, as students eventually learn.

**Comment by crossroads1112** [comment]
@dmalan This solution would fail if a line were given that ended in a CR however, IIRC only pre-OSX Macs use a single CR as a line break. LF and CRLF could be easily handled but would require a small helper function (I know, we like to avoid those).
 
Something like:

    void remove_newlines(string s)
    {
        size_t len = strlen(s);
        for (size_t i = len - 2; i < len; i++)
        {
            if (s[i] == '\n' || s[i] == '\r')
            {
               s[i] = '\0';
           }
        }
    }

**Comment by crossroads1112** [comment]
Another thing `getline` does differently is it does not minimize the buffer as the cs50 library does currently. This could be easily added to the `get_line` function in my edit above if necessary, however.

**Comment by dmalan** [comment]
After some thought and conferring with @glennholloway, feels simplest to leverage our own garbage collector and simply have `get_{chat,double,float,int,long,long_long}` not free anything, relying instead on our own destructor. Much as I like the cleanliness of having only `get_string` leak memory, adding more code to deal with leading whitespace and disparate line endings feels like undue complication, particularly since we're leaking (and garbage-collecting) so relatively few bytes. Let's leave the leaks (for now, at least), the messaging being that the library indeed leaks at least one byte for each `char` a user inputs via `stdin` until its destructor kicks in. "But there's a better way" is the teachable moment mid-semester.
