### ISSUE TITLE
re-add GetString for backwards-compatibility with CS50x 2016

### ISSUE THREAD

**Issue by dmalan** [cs50/lib50-c#40]
So that if a student calls `GetString` and then calls `free` on its return value, as previously taught, new library doesn't double-free it.

**Comment by kzidane** [comment]
Not really. A double free or corruption error is thrown.

**Comment by dmalan** [comment]
*try to double-free it. 😛

**Comment by kzidane** [comment]
Yes. :smile:

**Comment by FreeER** [comment]
Hm, so is the goal to simply replace the new get_string function with the original, or re-add the original GetString under another name that students could set GetString to so that they have a version that does not free the strings (assuming they know that a change has happened and they can do so to get the original behavior)?

To avoid code duplication you could have two wrapper functions that call a get_string that takes a bool saying whether to manage the allocated memory or not and GetString is set to the managing one by default (too bad C doesn't have default args here)... Or maybe a (const?) global variable that get_string checks, not really sure which method is better though I don't know much about extern variables so I'd assume there are some potential issues with that approach.

**Comment by dmalan** [comment]
Given that we're planning to deprecate `Get*` forcibly in January 2017 (thereafter removing altogether), short-term code duplication feels okay so that students can continue to read and understand each of `GetString` and `get_string` independently of the other!
