### ISSUE TITLE
56199 Segmentation fault

### ISSUE THREAD

**Issue by Sendoushi** [cs50/lib50-c#55]
I'm using the `cs50.h` directly and getting a `56199 Segmentation fault`.

Here is my `hello.c`:
```c
#include "../../../github.com/cs50/lib50-c/src/cs50.h"
#include <stdio.h>

// Main project method
int main(void) {
    string s = get_string();
}
```

Build command is a simple `make`:
```sh
make hello
```

This also happens when I include the built header instead or if I have the header under `/usr/include`.
I'm working under `Mac OS`. Does this work only under `linux`?

**Comment by ehzShelter** [comment]
@Sendoushi No, It will work in almost every OS. Your are getting this error because your linker are failing...

So, **_two solution_** for this.. 
Solution 1 : more stable and handy
Make static library of this cs50 library by following these procedure
```bash
gcc -c -ggdb -std=c99 cs50.c -o cs50.o
ar rcs libcs50.a cs50.o
rm -f cs50.o
chmod 0644 cs50.h libcs50.a
sudo mkdir -p /usr/local/include
sudo mv -f cs50.h /usr/local/include
sudo mkdir -p /usr/local/lib
sudo mv -f libcs50.a /usr/local/lib
```

or compile evary program this way
clang -ggdb3 -O0 -std=c99 hello.c ../../../github.com/cs50/lib50-c/src/cs50.c -o hello

If you want to use gcc compiler, then
gcc -g -std=c99 hello.c ../../../github.com/cs50/lib50-c/src/cs50.c -o hello

**Remember, when you are compile this way, don't use .h files in CLI.**

_Here I am assuming your file relative path according to your ../../../github.com/cs50/lib50-c/src/cs50.h directory_

Reference :
https://manual.cs50.net/library/
http://stackoverflow.com/questions/5965171/what-is-a-file-with-extension-a

**Comment by Sendoushi** [comment]
You're assuming it right :)

**Comment by Bramas** [comment]
Hello,
I had the error too and I don't think it is a problem with the linker. 
The symbol `get_string` exists in a system lib (on Mac OS X) and is getting called instead of the cs50 version.
I resolved it by ensuring that I link -lcs50 first

maybe the naming convention for cs50 lib is not the best as it permits this conflict.
Something like `cs50_get_string`,  or with another prefix, should be used to avoid future conflicts and seeing the same prefix for all the function of a given lib is something students will see in any lib in the future anyway.
